### ISSUE TITLE
Messed up "Umlaut"

### ISSUE THREAD

**Issue by StefanG3D** [SaschaWillems/vulkan.gpuinfo.org#69] opened 2023-07-06 05:38 UTC
I noticed a user name with a messed up umlaut here:
https://vulkan.gpuinfo.org/displayreport.php?id=22343
After clicking the user name his record list appears empty.

**Comment by SaschaWillems** [comment] 2023-10-18 19:04
This seems to be caused by a server setting that I can't influence. As this is a very minor thing, I'll just close it.

**Closed by SaschaWillems** 2023-10-18 19:04 UTC
